apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*

build:
    local:
        push: false
    artifacts:
    - image: neilmichaeli/client
      context: client
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: 'src/**/*.js'
                  dest: .
    - image: neilmichaeli/posts
      context: posts
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: '*.js'
                  dest: .
    
    - image: neilmichaeli/comments
      context: comments
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: '*.js'
                  dest: .
    
    - image: neilmichaeli/event-bus
      context: event-bus
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: '*.js'
                  dest: .
    
    - image: neilmichaeli/query
      context: query
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: '*.js'
                  dest: .
    
    - image: neilmichaeli/moderation
      context: moderation
      docker:
            dockerfile: Dockerfile
      sync:
            manual:
                - src: '*.js'
                  dest: .
    
